server:
  port: 8003
spring:
  application:
    name: eureka-sever
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
    fetch-registry: true
    register-with-eureka: true