server:
  port: 8002
spring:
  application:
    name: eureka-sever
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8003/eureka/
    fetch-registry: true
    register-with-eureka: true